"""Pydantic models for request/response validation and CSV schema enforcement."""

from pydantic import BaseModel, field_validator


class SalesRow(BaseModel):
    """Validates a single row from the sales CSV after Pandas loads it.

    Attributes:
        SKU: Product identifier string.
        Shopify_Units_M1: Shopify unit sales, oldest month.
        Shopify_Units_M2: Shopify unit sales, second month.
        Shopify_Units_M3: Shopify unit sales, third month.
        Shopify_Units_M4: Shopify unit sales, most recent month.
        Amazon_Units_M1: Amazon unit sales, oldest month.
        Amazon_Units_M2: Amazon unit sales, second month.
        Amazon_Units_M3: Amazon unit sales, third month.
        Amazon_Units_M4: Amazon unit sales, most recent month.
        Stock_On_Hand: Current warehouse inventory in units.
        Units_On_Order: Inventory currently in transit or manufacturing.
        Order_Arrival_Months: Lead time for new orders (months).
        Target_Months_Cover: Desired safety stock level (months of supply).
        Retail_Price_USD: Retail price per unit in USD.
    """

    SKU: str
    Shopify_Units_M1: int
    Shopify_Units_M2: int
    Shopify_Units_M3: int
    Shopify_Units_M4: int
    Amazon_Units_M1: int
    Amazon_Units_M2: int
    Amazon_Units_M3: int
    Amazon_Units_M4: int
    Stock_On_Hand: int
    Units_On_Order: int
    Order_Arrival_Months: int
    Target_Months_Cover: int
    Retail_Price_USD: float

    @field_validator("Retail_Price_USD")
    @classmethod
    def price_must_be_positive(cls, v: float) -> float:
        """Ensure retail price is positive."""
        if v <= 0:
            raise ValueError("Retail_Price_USD must be positive")
        return v


class SOPMetrics(BaseModel):
    """Top-level KPI summary for the dashboard.

    Attributes:
        total_m4_revenue: Sum of Revenue_M4 across all SKUs.
        skus_at_risk: Count of SKUs where Is_At_Risk is True.
    """

    total_m4_revenue: float
    skus_at_risk: int


class RedFlagItem(BaseModel):
    """Data for a single at-risk SKU displayed in the dashboard table.

    Attributes:
        SKU: Product identifier.
        Effective_Months_Cover: Months of cover including in-transit stock.
        Target_Months_Cover: Company's desired minimum cover.
        Suggested_Reorder_Qty: Calculated units to order today.
        Revenue_M4: Most recent month's revenue contribution.
    """

    SKU: str
    Effective_Months_Cover: float
    Target_Months_Cover: int
    Suggested_Reorder_Qty: int
    Revenue_M4: float


class SOPResponse(BaseModel):
    """Full API response from GET /api/v1/generate-sop.

    Attributes:
        status: Always "success" on a 200 response.
        metrics: Top-level KPI summary.
        red_flag_data: List of at-risk SKUs for dashboard rendering.
        llm_briefing: Markdown string generated by the LLM.
    """

    status: str
    metrics: SOPMetrics
    red_flag_data: list[RedFlagItem]
    llm_briefing: str
